### ISSUE TITLE
InflateException when trying to implement ImageViewNext

### ISSUE THREAD

**Issue by alexkong1** [frapontillo/ImageViewEx#16]
I'm trying to implement ImageViewNext to display an animated gif from a URL, but I keep getting InflateException when I add it to my layout.  I'm not really sure why.  It fails when trying to inflate the layout from a support-v4 Fragment.  Should I include the logcat?

```
            @Override
    public View onCreateView(LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {

        View root = inflater.inflate(R.layout.card, container, false);
        initializeUi(root);
        return root;
    }
```

My code is

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_marginLeft="@dimen/viewpager_margin_fix"
              android:layout_marginRight="@dimen/viewpager_margin_fix"
              android:layout_width="match_parent"
              android:layout_height="wrap_content">

    <net.frakbot.imageviewex.ImageViewNext
        android:id="@+id/background"
        android:layout_height="@dimen/card_height"
        android:layout_width="@dimen/card_width"
        android:layout_gravity="center"
        android:layout_marginTop="@dimen/card_top_offset"
        android:layout_centerHorizontal="true"/>

</RelativeLayout>
```

**Comment by rock3r** [comment]
Yes, it's definitely needed. The issue could be literally anything.

**Comment by alexkong1** [comment]
```
03-11 14:44:29.904    1100-1100/com.example.test E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #8: Error inflating class net.frakbot.imageviewex.ImageViewNext
            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at com.example.test.fragment.CardFragment.onCreateView(CardFragment.java:72)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
            at android.view.View.measure(View.java:15172)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
            at android.view.View.measure(View.java:15172)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:15172)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
            at android.view.View.measure(View.java:15172)
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:651)
            at android.view.View.measure(View.java:15172)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:15172)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
            at android.view.View.measure(View.java:15172)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2148)
            at android.view.View.measure(View.java:15172)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1848)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1100)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1273)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:525)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.Zygote
```

**Comment by rock3r** [comment]
It doesn't show any item in the stack trace that helps understanding the issue (nor any that is in the NIVE codebase). You sure you have the library correctly set up in your classpath? Given the spot where it crashes, it could be the issue here.

**Comment by alexkong1** [comment]
Alright.  I'll try playing around with it.  I kinda expected some possible dependency issues since my project uses a Maven set up for dependencies and I just tried to add this in as a module.  But as far as I know, I set it up like the sample app in the test folder, which worked for me.

**Comment by rock3r** [comment]
You could try checking if the apk file that is built by Maven contains the class, for example by using apktool to decompile it.

**Comment by alexkong1** [comment]
Thanks for the suggestion.  I see that Maven is not picking up the library.  I guess I'll play around with the maven settings or see if I can maven-ize the library.

**Comment by rock3r** [comment]
No problem. A user has added the library to some Maven repo, you might want to use that. See [issue #12](https://github.com/frapontillo/ImageViewEx/issues/12#issuecomment-35743650).

**Comment by alexkong1** [comment]
I tried that using that repo, but there were a few version conflicts with other dependencies in my repository.  It did give me a good starting point to set up my own POM file, though.  I have some of it working, but I'm having trouble reading the styleables from the generated R file, which give me a compilation failure on ImageViewEx.java.  I'm still making adjustments, so hopefully I'll figure out the issue at some point.
